// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LeaderElectionColumns holds the columns for the "leader_election" table.
	LeaderElectionColumns = []*schema.Column{
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "resource_version", Type: field.TypeString, Default: "0"},
		{Name: "lease_duration_seconds", Type: field.TypeInt},
		{Name: "acquire_time", Type: field.TypeInt64},
		{Name: "renew_time", Type: field.TypeInt64},
		{Name: "leader_transitions", Type: field.TypeInt},
		{Name: "holder_identity", Type: field.TypeString},
	}
	// LeaderElectionTable holds the schema information for the "leader_election" table.
	LeaderElectionTable = &schema.Table{
		Name:       "leader_election",
		Columns:    LeaderElectionColumns,
		PrimaryKey: []*schema.Column{LeaderElectionColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LeaderElectionTable,
	}
)

func init() {
	LeaderElectionTable.Annotation = &entsql.Annotation{
		Table: "leader_election",
	}
}
