// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LeaderElect is the predicate function for leaderelect builders.
type LeaderElect func(*sql.Selector)
