// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yangsijie666/controller-manager/pkg/resourcelock/sqllock/ent/leaderelect"
	"github.com/yangsijie666/controller-manager/pkg/resourcelock/sqllock/ent/predicate"
)

// LeaderElectQuery is the builder for querying LeaderElect entities.
type LeaderElectQuery struct {
	config
	ctx        *QueryContext
	order      []leaderelect.OrderOption
	inters     []Interceptor
	predicates []predicate.LeaderElect
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LeaderElectQuery builder.
func (leq *LeaderElectQuery) Where(ps ...predicate.LeaderElect) *LeaderElectQuery {
	leq.predicates = append(leq.predicates, ps...)
	return leq
}

// Limit the number of records to be returned by this query.
func (leq *LeaderElectQuery) Limit(limit int) *LeaderElectQuery {
	leq.ctx.Limit = &limit
	return leq
}

// Offset to start from.
func (leq *LeaderElectQuery) Offset(offset int) *LeaderElectQuery {
	leq.ctx.Offset = &offset
	return leq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (leq *LeaderElectQuery) Unique(unique bool) *LeaderElectQuery {
	leq.ctx.Unique = &unique
	return leq
}

// Order specifies how the records should be ordered.
func (leq *LeaderElectQuery) Order(o ...leaderelect.OrderOption) *LeaderElectQuery {
	leq.order = append(leq.order, o...)
	return leq
}

// First returns the first LeaderElect entity from the query.
// Returns a *NotFoundError when no LeaderElect was found.
func (leq *LeaderElectQuery) First(ctx context.Context) (*LeaderElect, error) {
	nodes, err := leq.Limit(1).All(setContextOp(ctx, leq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{leaderelect.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (leq *LeaderElectQuery) FirstX(ctx context.Context) *LeaderElect {
	node, err := leq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LeaderElect ID from the query.
// Returns a *NotFoundError when no LeaderElect ID was found.
func (leq *LeaderElectQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = leq.Limit(1).IDs(setContextOp(ctx, leq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{leaderelect.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (leq *LeaderElectQuery) FirstIDX(ctx context.Context) string {
	id, err := leq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LeaderElect entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LeaderElect entity is found.
// Returns a *NotFoundError when no LeaderElect entities are found.
func (leq *LeaderElectQuery) Only(ctx context.Context) (*LeaderElect, error) {
	nodes, err := leq.Limit(2).All(setContextOp(ctx, leq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{leaderelect.Label}
	default:
		return nil, &NotSingularError{leaderelect.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (leq *LeaderElectQuery) OnlyX(ctx context.Context) *LeaderElect {
	node, err := leq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LeaderElect ID in the query.
// Returns a *NotSingularError when more than one LeaderElect ID is found.
// Returns a *NotFoundError when no entities are found.
func (leq *LeaderElectQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = leq.Limit(2).IDs(setContextOp(ctx, leq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{leaderelect.Label}
	default:
		err = &NotSingularError{leaderelect.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (leq *LeaderElectQuery) OnlyIDX(ctx context.Context) string {
	id, err := leq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LeaderElects.
func (leq *LeaderElectQuery) All(ctx context.Context) ([]*LeaderElect, error) {
	ctx = setContextOp(ctx, leq.ctx, "All")
	if err := leq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LeaderElect, *LeaderElectQuery]()
	return withInterceptors[[]*LeaderElect](ctx, leq, qr, leq.inters)
}

// AllX is like All, but panics if an error occurs.
func (leq *LeaderElectQuery) AllX(ctx context.Context) []*LeaderElect {
	nodes, err := leq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LeaderElect IDs.
func (leq *LeaderElectQuery) IDs(ctx context.Context) (ids []string, err error) {
	if leq.ctx.Unique == nil && leq.path != nil {
		leq.Unique(true)
	}
	ctx = setContextOp(ctx, leq.ctx, "IDs")
	if err = leq.Select(leaderelect.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (leq *LeaderElectQuery) IDsX(ctx context.Context) []string {
	ids, err := leq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (leq *LeaderElectQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, leq.ctx, "Count")
	if err := leq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, leq, querierCount[*LeaderElectQuery](), leq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (leq *LeaderElectQuery) CountX(ctx context.Context) int {
	count, err := leq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (leq *LeaderElectQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, leq.ctx, "Exist")
	switch _, err := leq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (leq *LeaderElectQuery) ExistX(ctx context.Context) bool {
	exist, err := leq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LeaderElectQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (leq *LeaderElectQuery) Clone() *LeaderElectQuery {
	if leq == nil {
		return nil
	}
	return &LeaderElectQuery{
		config:     leq.config,
		ctx:        leq.ctx.Clone(),
		order:      append([]leaderelect.OrderOption{}, leq.order...),
		inters:     append([]Interceptor{}, leq.inters...),
		predicates: append([]predicate.LeaderElect{}, leq.predicates...),
		// clone intermediate query.
		sql:  leq.sql.Clone(),
		path: leq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ResourceVersion string `json:"resource_version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LeaderElect.Query().
//		GroupBy(leaderelect.FieldResourceVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (leq *LeaderElectQuery) GroupBy(field string, fields ...string) *LeaderElectGroupBy {
	leq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LeaderElectGroupBy{build: leq}
	grbuild.flds = &leq.ctx.Fields
	grbuild.label = leaderelect.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ResourceVersion string `json:"resource_version,omitempty"`
//	}
//
//	client.LeaderElect.Query().
//		Select(leaderelect.FieldResourceVersion).
//		Scan(ctx, &v)
func (leq *LeaderElectQuery) Select(fields ...string) *LeaderElectSelect {
	leq.ctx.Fields = append(leq.ctx.Fields, fields...)
	sbuild := &LeaderElectSelect{LeaderElectQuery: leq}
	sbuild.label = leaderelect.Label
	sbuild.flds, sbuild.scan = &leq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LeaderElectSelect configured with the given aggregations.
func (leq *LeaderElectQuery) Aggregate(fns ...AggregateFunc) *LeaderElectSelect {
	return leq.Select().Aggregate(fns...)
}

func (leq *LeaderElectQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range leq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, leq); err != nil {
				return err
			}
		}
	}
	for _, f := range leq.ctx.Fields {
		if !leaderelect.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if leq.path != nil {
		prev, err := leq.path(ctx)
		if err != nil {
			return err
		}
		leq.sql = prev
	}
	return nil
}

func (leq *LeaderElectQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LeaderElect, error) {
	var (
		nodes = []*LeaderElect{}
		_spec = leq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LeaderElect).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LeaderElect{config: leq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, leq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (leq *LeaderElectQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := leq.querySpec()
	_spec.Node.Columns = leq.ctx.Fields
	if len(leq.ctx.Fields) > 0 {
		_spec.Unique = leq.ctx.Unique != nil && *leq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, leq.driver, _spec)
}

func (leq *LeaderElectQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(leaderelect.Table, leaderelect.Columns, sqlgraph.NewFieldSpec(leaderelect.FieldID, field.TypeString))
	_spec.From = leq.sql
	if unique := leq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if leq.path != nil {
		_spec.Unique = true
	}
	if fields := leq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, leaderelect.FieldID)
		for i := range fields {
			if fields[i] != leaderelect.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := leq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := leq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := leq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := leq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (leq *LeaderElectQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(leq.driver.Dialect())
	t1 := builder.Table(leaderelect.Table)
	columns := leq.ctx.Fields
	if len(columns) == 0 {
		columns = leaderelect.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if leq.sql != nil {
		selector = leq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if leq.ctx.Unique != nil && *leq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range leq.predicates {
		p(selector)
	}
	for _, p := range leq.order {
		p(selector)
	}
	if offset := leq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := leq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LeaderElectGroupBy is the group-by builder for LeaderElect entities.
type LeaderElectGroupBy struct {
	selector
	build *LeaderElectQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (legb *LeaderElectGroupBy) Aggregate(fns ...AggregateFunc) *LeaderElectGroupBy {
	legb.fns = append(legb.fns, fns...)
	return legb
}

// Scan applies the selector query and scans the result into the given value.
func (legb *LeaderElectGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, legb.build.ctx, "GroupBy")
	if err := legb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LeaderElectQuery, *LeaderElectGroupBy](ctx, legb.build, legb, legb.build.inters, v)
}

func (legb *LeaderElectGroupBy) sqlScan(ctx context.Context, root *LeaderElectQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(legb.fns))
	for _, fn := range legb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*legb.flds)+len(legb.fns))
		for _, f := range *legb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*legb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := legb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LeaderElectSelect is the builder for selecting fields of LeaderElect entities.
type LeaderElectSelect struct {
	*LeaderElectQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (les *LeaderElectSelect) Aggregate(fns ...AggregateFunc) *LeaderElectSelect {
	les.fns = append(les.fns, fns...)
	return les
}

// Scan applies the selector query and scans the result into the given value.
func (les *LeaderElectSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, les.ctx, "Select")
	if err := les.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LeaderElectQuery, *LeaderElectSelect](ctx, les.LeaderElectQuery, les, les.inters, v)
}

func (les *LeaderElectSelect) sqlScan(ctx context.Context, root *LeaderElectQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(les.fns))
	for _, fn := range les.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*les.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := les.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
